### PR TITLE
Adding @zamfi as facilitator to computer networks session in calendar.html

### PR DESCRIPTION
**Pull request by zamfi**
Happy to run an interactive session that I've done before or just be around to answer questions and offer thoughts!

### CODE REVIEW

**Comment by morenoh149** [comment]
I'm assuming it's way too late to merge this @zamfi

**Comment by zamfi** [comment]
Hah, yeah I suppose. :) But I did present, so maybe useful for historical
reasons?

**Comment by morenoh149** [comment]
mind resolving conflicts?

**Comment by zamfi** [comment]
Ah, actually, my session was at the January institute, not August. So, never mind!

**Pull request closed without merging**
